name: attendance_app
description: "Professional Face Recognition Attendance System for MIT"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # --- AI & Image Processing ---
  camera: ^0.11.0
  google_mlkit_face_detection: ^0.13.2
  tflite_flutter: ^0.10.0 # Runs the MobileFaceNet model
  image: ^4.1.3           # For image manipulation/resizing

  # --- Sensors & Location ---
  geolocator: ^12.0.0
  permission_handler: ^11.3.1 # Handles Android camera/GPS permissions

  # --- Data Persistence ---
  sqflite: ^2.3.0
  path_provider: ^2.1.0
  path: ^1.9.0

  # --- UI & State Management ---
  intl: ^0.19.0
  provider: ^6.1.5+1
  cupertino_icons: ^1.0.6
  geocoding: ^4.0.0
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # IMPORTANT: Add your TFLite model here later
  assets:
    - assets/mobile_face_net.tflite